[project]
name = "test-crx-kinematics"
version = "0.3.1"
description = "Tester for Fanuc CRX kinematics solver for RoboDK"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.12"
dependencies = [
    "hypothesis>=6.168.5",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "robodk>=6.0.2",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(levelname)s %(message)s"
# addopts = "-q"
# If Tracebacks are too long, use --tb=line to shorten 
addopts = "-q --tb=line -ra"

testpaths = ["tests"]
